### ISSUE TITLE
Examples no longer working

### ISSUE THREAD

**Issue by mleonard87** [Fivium/jquery-tagger#47]
I receive the following error for various resources when browsing the gh-pages hosted examples:

```
Mixed Content: The page at 'https://fivium.github.io/jquery-tagger/examples.htm' was loaded
over HTTPS, but requested an insecure stylesheet 'http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css'.
This request has been blocked; the content must be served over HTTPS.
```

**Comment by Palmr** [comment]
Can't reproduce here, what browser are you using?

**Comment by mleonard87** [comment]
Chrome - just realised that the https everywhere is redirecting me to https version of the examples rather than the http version that is actually linked. Should probably be using this and update the readme too.

**Comment by Palmr** [comment]
Ahh, next you'll be raising issues that the examples don't work when using noscript! :stuck_out_tongue_closed_eyes: 

The pull you sent seems fine, though you should update the examples htm in the master branch too.

**Comment by Palmr** [comment]
Cheers @mleonard87
